language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'

before_script: 
  - phpenv config-add travis.ini
  - composer require phpunit/phpunit:8.*.* satooshi/php-coveralls:dev-master
  - composer install --dev

script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v