language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'

before_script:
  - composer require "mezon/router:>=1.0.0"
  - composer require "mezon/template-engine:>=1.0.0"
  - composer require "mezon/functional:>=1.0.0"
  - composer require "mezon/singleton:>=1.0.0"
  - composer require "mezon/utils:>=1.0.0"
  - composer require "mezon/cache:>=1.0.0"
  - composer require "mezon/conf:>=1.0.0"
  - composer require "mezon/pdocrud:>=1.0.0"
  - composer require "mezon/custom-client:>=1.0.0"
  - composer require "mezon/security:>=1.0.0"
  - composer require "mezon/application:>=1.0.0"
  - composer require "mezon/dns-client:>=1.0.0"
  - composer require "mezon/gui:>=1.0.0"
  - composer require "mezon/service:>=1.0.0"
  - composer require "mezon/crud-service:>=1.0.0"
  - composer require "mezon/gentella:>=1.0.0"
  - composer require "mezon/social-network:>=1.0.0"
  - composer require "mezon/service-client:>=1.0.0"
  - composer require "mezon/crud-service-client:>=1.0.0"
  - composer require "mezon/crud-service-collection:>=1.0.0"
  - composer require "mezon/crud-service-client-adapter:>=1.0.0"
  - composer require "mezon/application-actions:>=1.0.0"

script:
  - phpunit --coverage-clover=coverage.xml --configuration=phpunit.xml

after_script:
 - bash <(curl -s https://codecov.io/bash)