language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'

before_script: 
  - phpenv config-add travis.ini
  - composer require phpunit/phpunit:8.*.*
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
 - bash <(curl -s https://codecov.io/bash)